# Generated by Django 3.1.5 on 2021-05-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210507_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetail',
            name='remarks',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
