# Generated by Django 3.1.5 on 2021-05-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountdetail_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='remarks',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
