# Generated by Django 3.1.5 on 2021-05-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210508_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdetail',
            old_name='credit',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='accountdetail',
            name='debit',
        ),
    ]
